acasi-ctf/ctf

.github/workflows/ui-build.yaml

This pull request adds a GitHub Actions workflow that will ensure npm is working correctly and the UI JavaScript builds.

Add GitHub Action for UI Build

---

.github/workflows/super-linter.yaml
Makefile
challenges/Challenge-Set-1/Challenges/Cipher-challenge/Caesar-cipher.py
challenges/Challenge-Set-1/Challenges/Cipher-challenge/Letter-to-Number.py
challenges/Challenge-Set-1/Challenges/Cipher-challenge/Mixed-Challenge-1.py
challenges/Challenge-Set-1/Challenges/Cipher-challenge/Morse_code.py
challenges/Challenge-Set-1/Challenges/Cipher-challenge/Reverse.py

These are the python files for the cipher files.

added cipher python files to repo

---

.github/linters/.markdown-lint.yml
README.md
frontend/__init__.py
frontend/api.yaml
frontend/app.py
frontend/extensions.py
frontend/main.py
frontend/model/challenges.py
frontend/routes/__init__.py
frontend/routes/api/__init__.py
frontend/routes/api/admin_challenges.py
frontend/routes/api/challenges.py
frontend/settings.py
retros/Sprint2_RetroSummary.md

* Added documentation for sprint 2 retrospective.
* No video for Sponsor demo until Friday.
* Enable MD024 allow_different_nesting rule.

Sprint 2 + Retro Summary

---

README.md

Add the sprint 2 demo link to the README.

Add sprint 2 demo link

---

challenges/Challenge-Set-1/Docs/Morse_code.md

File did not update from original pull request.

Updating morse code documentation. Reformatting last example.

---

ui/.env
ui/package.json
ui/src/App.js
ui/src/Page/ChallengeSet1.css
ui/src/Page/ChallengeSet1.js
ui/src/Page/ChallengeSet1Data.js
ui/src/Page/Selection.css
ui/src/Page/Selection.js
ui/src/components/AppBar.js
ui/src/components/Menu.js
ui/src/components/MenuBarData.js
ui/src/components/SubMenu.js
ui/src/components/Terminal.css

- Updatable banner
- Getting started on API
- Created a bunch of cards, each represents a challenge (all link to challenge 1). just to show the wrapper function properly
- Terminal only shows up on challenge's page (not like on every pages as its used to)

Updatable banner

---

challenges/Challenge-Set-1/DirTrav-Challenge/DirTrav.md
challenges/Challenge-Set-1/DirTrav-Challenge/DirTravDescription.md
challenges/Challenge-Set-1/WebStruct-Challenge/BrowserTools.md
challenges/Challenge-Set-1/WebStruct-Challenge/CSS.md
challenges/Challenge-Set-1/WebStruct-Challenge/HTML.md
challenges/Challenge-Set-1/WebStruct-Challenge/PHP.md
challenges/Challenge-Set-1/WebStruct-Challenge/WebStructureDescript.md

Documentation for WebPage Struct

---

.github/workflows/operator-build-test.yaml
operator/build.gradle.kts
operator/gradle/wrapper/gradle-wrapper.properties
operator/src/main/kotlin/org/acasictf/ctf/operator/main.kt
operator/src/main/kotlin/org/acasictf/ctf/operator/persistence/EnvironmentDao.kt
operator/src/main/kotlin/org/acasictf/ctf/operator/persistence/ProxyPublicKey.kt
operator/src/main/kotlin/org/acasictf/ctf/operator/provisioner/KubernetesProvisioner.kt
operator/src/main/kotlin/org/acasictf/ctf/operator/service/LookupService.kt
operator/src/main/kotlin/org/acasictf/ctf/operator/service/ProvisioningService.kt
operator/src/main/kotlin/org/acasictf/ctf/operator/utils.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/TestChallengeId.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/model/ModelTest.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/persistence/ChallengeTemplateTest.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/persistence/EnvironmentDaoTest.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/persistence/FakeChallengeTemplate.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/persistence/ProxyPublicKeyTest.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/persistence/ResourceChallengeTemplate.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/persistence/StringChallengeTemplateFile.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/provisioner/KubernetesProvisionerTest.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/service/FakePersistenceLayer.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/service/LookupServiceTest.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/service/ProvisioningServiceTest.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/testutil/assert.kt
operator/src/test/kotlin/org/acasictf/ctf/operator/testutil/util.kt
operator/src/test/resources/README.md

This pull request adds a number of Operator tests to help increase code coverage, and upgrades to Gradle 7. Includes refactoring to allow for easier testing.

More Operator testing

---

README.md
operator/src/main/kotlin/org/acasictf/ctf/operator/service/ProvisioningService.kt
retros/Sprint3_RetroSummary.md

This is the last pull request before we finish sprint 3, it adds a retrospective summary and some minor information that is needed for our sprint summary.

Finalize sprint 3 documentation

---

ui/src/components/AppBarActions.js
ui/src/components/Spinner.jsx
ui/src/pages/ChallengeSetPage.js

* Created a loading animation to show the user that something is happening when they are waiting for an environment to build.
* Applied animation to the Challenge Set Page.
* Tested animation on temporarily unused score board page.

Fixed Loading animation component and applied to the page.

---

ui/package-lock.json
ui/package.json
ui/src/App.js
ui/src/components/Menu.js
ui/src/components/MenuBarData.js
ui/src/components/SubMenu.js
ui/src/pages/CaeserCipher.js
ui/src/pages/Selection.js

@lgorence I want to get Richards code merged into main so I can just do the file rearrangement quick and try and merge only that in and then see if I can merge in code changes.

Dynamic ui

---

ui/package-lock.json
ui/package.json
ui/src/App.js
ui/src/components/AppBar.js
ui/src/components/AppBarActions.js
ui/src/components/Menu.js
ui/src/components/SubMenu.js
ui/src/pages/ChallengePage.js
ui/src/style/App.css
ui/src/style/ChallengePage.css
ui/src/style/Terminal.css

---
- Adjusting display of contents to match with different screen resolution
- Reloading the page will redirect to home page
- Repleace show environment button with submit flag button that will later appear base challenge API. When click on submit flag, it will:
- If input field is not in display, make it show up,
- If it is already in display, later will check on the flag
- If click on other challenge when it input field is already in display, erase the value inside input field(if there is any), and hide the field

Sprint6 richard

---

ui/src/components/Terminal.tsx

This pull request fixes a bug where if a challenge environment is started, the backing terminal PTY will not have the correct rows and columns. This was fixed by sending a resize message upon the first message that was sent from the Termproxy layer. Fixes #189.
Manual testing was performed to ensure the correct behavior is exhibited.

Fix terminal size not being correct unless first resized.

---

frontend/routes/api/challenges.py

This pull request implements the trending challenges API, which is effectively the same thing as the top challenges API, but only accounts for the last 14 days.
Done in collaboration with @colbycocking.
Closes #142.
The API did not exist prior to today.
Linked is a GitHub Gist which contains the contents of this API response.
https://gist.github.com/lgorence/e739927865213325404ef555f778876e

Implement trending challenges API.

---

Makefile
challenges/games/challenges/noughts/src/Noughts.java
challenges/games/challenges/prize/src/Prize.java
challenges/games/challenges/rock-paper-scissors/src/RockPaperScissors.java
challenges/games/challenges/seven-up/src/SevenUp.java

When the following java games were attempted to be run, they would throw an error:
- Seven Up
- Prize
- Noughts
- Rock Paper Scissors
- Fixed all the java games so that they run when you type in the start commands. They were all missing the args[] parameter.

Initial clean up of games challenge set.

---

ui/src/components/AppBar.js
ui/src/components/AppBarActions.js
ui/src/components/Menu.js
ui/src/components/NotificationToast.js
ui/src/pages/ChallengePage.js
ui/src/pages/LeaderBoard.js
ui/src/pages/Selection.js
ui/src/style/ChallengePage.css
ui/src/style/LeaderBoard.css
ui/src/style/NotificationToast.css

- Swapped around the terminal and the Documentations
- Added a leaderboad based on whatever the user in api
- display the documentation based on the order property in the api
- Added a toast for notification when submit flag is correct/incorrect
- #191 
- #204 
- #193
- #186

Sprint7 richard UI

---

ui/src/components/AppBar.js
ui/src/components/Menu.js

Fixed the bug of unable to open the submit flag input field

Fixed submit flag bug

---

challenges/pentesting/challenges/Tools.md

Put together a list of useful Kali/Linux tools, provided descriptions, installation commands and links for more info. 
Closes #136

ei-added useful tools file

---

challenges/pentesting/challenge-set.json

Due to my inability to resolve the issues occurring when running Hashcat on the webpage I went ahead and removed it from the challenge set so it wouldn't be part of the demo.

Removed Hashcat from challenge set

---

challenges/ciphers/challenges/comprehensive-challenge/docs/Mixed-Challenge.md

Changed Mixed-Challenge to Comprehensive-Challenge in Mixed-Challenge.md file

Changed Mixed-Challenge to Comprehensive-Challenge
